import '../../../core/database/app_database.dart';
import '../../../core/logging/app_logger.dart';
import '../data/article_source_client.dart';
import '../domain/news_article.dart';

const String readingNoteTypeWord = 'word';
const String readingNoteTypeGrammar = 'grammar';

class ImmersionRepository {
  ImmersionRepository(this.database, {ArticleSourceClient? articleSourceClient})
    : _articleSourceClient = articleSourceClient ?? ArticleSourceClient();

  final AppDatabase database;
  final ArticleSourceClient _articleSourceClient;

  void dispose() {
    _articleSourceClient.dispose();
  }

  Future<ReadingDocument> prepareDocument(NewsArticle article) {
    final script = article.readingScript;
    AppLogger.info(
      'ImmersionRepository',
      'Preparing reading document.',
      details: <String, Object?>{
        'url': article.url,
        'scriptLength': script.length,
        'truncated': article.isContentTruncated,
      },
    );

    return database.upsertReadingDocument(
      sourceUrl: article.url,
      sourceTitle: article.title,
      sourceName: article.sourceName,
      description: article.description,
      scriptText: script,
      publishedAt: article.publishedAt,
    );
  }

  Future<void> updateScript(int documentId, String scriptText) {
    AppLogger.info(
      'ImmersionRepository',
      'Updating reading script.',
      details: <String, Object?>{
        'documentId': documentId,
        'scriptLength': scriptText.trim().length,
      },
    );
    return database.updateReadingScript(documentId, scriptText);
  }

  Future<ArticleContentSyncResult> enrichDocumentFromSource({
    required NewsArticle article,
    required ReadingDocument document,
  }) async {
    final currentScript = document.scriptText.trim();
    final generatedScript = article.readingScript.trim();
    final normalizedCurrent = _normalizeComparableText(currentScript);
    final normalizedGenerated = _normalizeComparableText(generatedScript);

    if (!article.requiresSourceEnrichment) {
      return ArticleContentSyncResult(
        document: document,
        message: '현재 기사 응답만으로 읽기용 본문이 충분합니다.',
      );
    }

    final looksAutoGenerated =
        normalizedCurrent.isEmpty ||
        normalizedCurrent == normalizedGenerated ||
        (normalizedCurrent.startsWith(_normalizeComparableText(article.title)) &&
            normalizedCurrent.contains(
              _normalizeComparableText(article.description),
            ) &&
            normalizedCurrent.length <= normalizedGenerated.length + 120);
    if (!looksAutoGenerated) {
      AppLogger.info(
        'ImmersionRepository',
        'Skipping source sync because the document looks user-edited.',
        details: <String, Object?>{
          'documentId': document.id,
          'url': article.url,
        },
      );
      return ArticleContentSyncResult(
        document: document,
        message: '직접 수정한 스크립트가 있어 자동 덮어쓰기를 건너뛰었습니다.',
      );
    }

    final sourceBody = await _articleSourceClient.fetchReadableBody(article.url);
    if (sourceBody == null || sourceBody.trim().isEmpty) {
      return ArticleContentSyncResult(
        document: document,
        message:
            '원문 본문을 자동으로 가져오지 못했습니다. 현재는 정리된 제목과 요약 본문을 사용합니다.',
      );
    }

    final nextScript = article.buildReadingScript(bodyOverride: sourceBody);
    if (nextScript.trim().isEmpty || nextScript.trim() == currentScript) {
      return ArticleContentSyncResult(
        document: document,
        message: '추가로 반영할 원문 본문이 없었습니다.',
      );
    }

    AppLogger.info(
      'ImmersionRepository',
      'Applying enriched source body to reading document.',
      details: <String, Object?>{
        'documentId': document.id,
        'url': article.url,
        'scriptLength': nextScript.length,
      },
    );
    await database.updateReadingScript(document.id, nextScript);
    final updatedDocument = await database.getReadingDocumentById(document.id);
    return ArticleContentSyncResult(
      document: updatedDocument,
      message: '원문에서 더 긴 본문을 찾아 반영했습니다.',
    );
  }

  Stream<List<ReadingNote>> watchWordNotes(int documentId) {
    return database.watchReadingNotes(
      documentId,
      noteType: readingNoteTypeWord,
    );
  }

  Stream<List<ReadingNote>> watchGrammarNotes(int documentId) {
    return database.watchReadingNotes(
      documentId,
      noteType: readingNoteTypeGrammar,
    );
  }

  Future<bool> toggleWordNote({
    required int documentId,
    required String surfaceText,
    required String normalizedText,
    String? meaning,
    String? explanation,
    String? contextSnippet,
  }) {
    return database.toggleReadingNote(
      documentId: documentId,
      noteType: readingNoteTypeWord,
      surfaceText: surfaceText,
      normalizedText: normalizedText,
      meaning: meaning,
      explanation: explanation,
      contextSnippet: contextSnippet,
    );
  }

  Future<bool> toggleGrammarNote({
    required int documentId,
    required String surfaceText,
    required String normalizedText,
    String? explanation,
    String? contextSnippet,
  }) {
    return database.toggleReadingNote(
      documentId: documentId,
      noteType: readingNoteTypeGrammar,
      surfaceText: surfaceText,
      normalizedText: normalizedText,
      explanation: explanation,
      contextSnippet: contextSnippet,
    );
  }
}

class ArticleContentSyncResult {
  const ArticleContentSyncResult({
    required this.document,
    required this.message,
  });

  final ReadingDocument document;
  final String message;
}

String _normalizeComparableText(String value) {
  return value.replaceAll(RegExp(r'\s+'), ' ').trim().toLowerCase();
}
